import assert from 'node:assert/strict';
import { readingMaterial, readingScopeInstruction } from '../src/reading-scope.js';
import { DEFAULT_PROMPTS, scopedQuickPrompts } from '../src/client/quick-prompts.js';
const selection = 'Translate only this sentence.';
const material = readingMaterial({ title:'Article', content:'Background that must not be translated.', selection });
assert.equal(material.operationTarget, 'selectedPassage');
assert.equal(material.selectedPassage, selection);
assert.equal(material.articleBackground, 'Background that must not be translated.');
assert.match(readingScopeInstruction(selection), /默认只处理这段选文/);
assert.match(readingScopeInstruction(selection), /只有用户本轮明确要求全文/);
assert.equal(readingMaterial({ content:'Article', selection:'' }).operationTarget, 'articleBackground');
assert.match(readingScopeInstruction(''), /不要把对话历史中的旧选段/);
const selected = scopedQuickPrompts(DEFAULT_PROMPTS, selection);
assert.match(selected.find(x => x.id === 'summary').body, /概括选中段落/);
assert.equal(selected.find(x => x.id === 'translate').title, '翻译选段');
assert.match(selected.find(x => x.id === 'translate').body, /不翻译全文/);
assert.equal(scopedQuickPrompts(DEFAULT_PROMPTS, '').find(x => x.id === 'explain').title, '解释文章');
const custom = { id:'summary', title:'全文总结', body:'请总结全文，不限选段。' };
assert.deepEqual(scopedQuickPrompts([custom], selection), [custom]);
assert.equal(readingMaterial({ content:'x'.repeat(30000), selection:'s'.repeat(6000) }).selectedPassage.length, 6000);
assert.equal(readingMaterial({ content:'x'.repeat(30000) }).articleBackground.length, 24000);
console.log('Reading scope: selection target, background separation, explicit whole-article request, removal and custom prompts passed');
